name: Robuxindo Tracker

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        run: npm install

      - name: Run Tracker
        run: node app.js
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
          GAS_URL: ${{ secrets.GAS_URL }}